### PR TITLE
Added new sum function and tests

### PR DESCRIPTION
**Pull request by josteinkjerstad**
Added new function to sum integers from a string with valid seperators such as \n or ,
Added tests to validate the new function

### CODE REVIEW

**Comment by josteinkjerstad** [comment]
#43 #42 #40 #41 #39

**Comment by josteinkjerstad** [comment]
#7 #8 #9 #10 #11

**Comment by josteinkjerstad** [comment]
#7 #8 #9 #10 #11

**Comment by hnformentin** [comment]
Thanks for the PR. I hope you appreciated the workshop. I will close it without merging due to the exercise nature of it.

**Pull request closed without merging**
